language: go

matrix:
  include:
    - os: linux
      env: DOCKER_PUSH=true
      services:
        - docker
    - os: osx
      # Do not start osx build for PR
    #   if: type != pull_request
    #   osx_image: xcode8
      env: DOCKER_PUSH=false

# services:
#   - docker

before_install:
  - if [[ "$DOCKER_PUSH" == "true" ]]; then docker build -t registry.luxair.tech/push-we .; fi

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
	  condition: $DOCKER_PUSH = true
